### PR TITLE
Support for factor treated vs response in full matching

### PR DESCRIPTION
**Pull request by cfhammill**
Adds a check if the formula LHS is a factor, sets treated be the second level, otherwise sets treated to be 1. Other labels or numbers are considered control.

Not sure if it is necessary to add checks that the factor has only two levels elsewhere in code.

### CODE REVIEW

**Comment by kosukeimai** [comment]
@cfhammill I need to take a closer look at this, but before I do that, can you fix the error?  Any pull request should not be failing the `travis-ci` check.

**Comment by cfhammill** [comment]
@kosukeimai it looks like a wide-spread problem afflicting all the PRs (and probably all travis builds). I'll open an issue

**Comment by kosukeimai** [comment]
Please try the approach mentioned #16 to see if it fixes the travis-ci check error. Thanks.

**Comment by cfhammill** [comment]
Build now passing

**Comment by ngreifer** [comment]
This issue has been fixed in the new update by transforming the treatment into a 0/1 variable. Thank you for this suggestion.

**Pull request closed without merging**
