### PR TITLE
Make `matchit2nearest` compatible with tibble

### PR DESCRIPTION
**Pull request by jlegewie**
`tibble` is a replacement for `data.frame` and part of the extremely popular tidyverse packages developed by Hadley Wickham (see tibble description [here](https://blog.rstudio.com/2016/03/24/tibble-1-0-0/)). `matchit2nearest` with the `exact` option is not compatible with `tibble`. The reason is that `tibble` always return a `tibble` and do not suddenly return a vector like `data.frame` for something like `df[1,1]`. This commit fixes the problem so that `matchit` with the `exact` option works when the user uses a `tibble` for the `data` argument. Here is some code to illustrate.

```
library("MatchIt")
library("tibble")

data(lalonde)
# works...
matchit(treat ~ re74 + re75 + age + educ, data = lalonde, method = "nearest", distance = "logit", exact = "black")
# matchit fails when I use a tibble for the data argument
matchit(treat ~ re74 + re75 + age + educ, data = as_tibble(lalonde), method = "nearest", distance = "logit", exact = "black")
# with this pull request, both data.frame and tibble work
```

### CODE REVIEW

**Comment by kosukeimai** [comment]
@jlegewie I need to take a closer look at this, but before I do that, can you fix the error?  Any pull request should not be failing the `travis-ci` check.

**Comment by kosukeimai** [comment]
Please try the approach mentioned #16 to see if it fixes the travis-ci check error. Thanks.

**Comment by jlegewie** [comment]
That fixed the travis-ci check.

**Comment by ngreifer** [comment]
All methods are now compatible with tibbles in the new update. Thank you for your suggestion!

**Pull request closed without merging**
