### PR TITLE
updates to MatchIt - including S3 method get_matches

### PR DESCRIPTION
**Pull request by alexWhitworth**
This pull request provides numerous updates.

1. Firstly, I consolidate all class methods within a single script `R/class_functions.R`
2. The new S3 method `get_matches` is added
3. The NAMESPACE is updated to using roxygen2 notes. 
4. the DESCRIPTION file has been updated. Most notably, several packages in the "suggests" line were moved to Depends. This is required for full functionality of the package and adheres to best practices for package development.
4a. Note that "cem" should also be moved to Depends; but currently the cem package does not load in R / is broken.
5. `tests/` were added. Note that all tests pass for `get_matches` with two exceptions-- for methods 'genetic' and 'cem'. 
    - CEM doesn't work as noted above. 
    - genetic doesn't work because there are problems with the underlying code `matchit2genetic`. This code needs to be rebased to have a return output that is similar to the other return methods.

I would further note that a full rebase of the matchit2* scripts would be a good idea. The various methods to `matchit` do **NOT** return the same output. Ideally, this should be fixed.

### CODE REVIEW

**Comment by alexWhitworth** [comment]
These test fails are expected -- see update item #5

**Comment by kosukeimai** [comment]
@alexWhitworth These are great improvements.  I have a few questions:

1.  Do syntaxes change?  I would like these changes not to affect users.
2. Did you check all the results?  We should have developed test scripts to do this, but at that time, we did not.  And yet there are many options and we want to make sure that this change does not break it.
3. Have you made any changes to plots and summaries?  Again, I want to make sure that users don't see changes.

Thanks for your contributions!

**Comment by alexWhitworth** [comment]
**Summary: my pull request does not create any new problems / is functional; but there are existing problems in the package that should be fixed. See details below.**

@kosukeimai There were no changes to the existing code. So there are no changes to syntax or plots/summaries (Q1, Q3).  

(Q2) I didn't write test scripts for your existing code, although I do note that CEM tests will not work since the CEM package will not load.  `cem` has a dependency on the `tcktk` package, which [no longer exists in R](https://cran.r-project.org/web/packages/tcltk/index.html). See below error message:

```
R> library(cem)
Loading required package: tcltk
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: X11 library is missing: install XQuartz from xquartz.macosforge.org
Error: package ‘tcltk’ could not be loaded
```

Because of the problems on CEM, the package will **not** pass `R CMD CHECK` and be accepted on CRAN. Though realistically, CRAN shouldn't accept the current version for the same reason. CRAN will also reject the tests on `get_matches` for the `matchit(... , method= "genetic")` This is because existing code to the genetic method is problematic.

I think it would be valuable to (A) fix the cem problem and (B) rebase your existing code so that your outputs to the different methods of `matchit` have the same return structure. Currently they do not. And the return to `method= genetic` is problematic as noted in my pull request.

Happy to discuss further over email or here.

**Comment by kosukeimai** [comment]
Thanks. @thegaryking Would you mind fixing the `cem` problem?  I will look into the genetic matching issue.

**Comment by alexWhitworth** [comment]
@kosukeimai look at the structure of `m.out$match.matrix` on this [one](https://github.com/alexWhitworth/MatchIt/blob/master/tests/test-get_matches.R#L177-L178)... there's a column of `NA` values that shouldn't be there.

**Comment by thegaryking** [comment]
Hi Alex, thanks for your great contributions.  On the CEM issues:  tcltk is included in any distribution of R. It is in base R.  Unfortunately, on the Mac you need to install X11, which is no longer included by Apple. See https://cran.r-project.org/bin/macosx/ which says: 

Note: the use of X11 (including tcltk) requires XQuartz to be installed since it is no longer part of OS X. Always re-install XQuartz when upgrading your OS X to a new major version.

It is annoying, but it is not just CEM. Dozens of packages, including tcltk2, have the same issue.

**Comment by alexWhitworth** [comment]
@thegaryking simple, self-inflicted, bugs are the best ones.

I've got another commit to update `get_matches` for `cem`. Now passing tests.

**Comment by alexWhitworth** [comment]
Though I note that I still get a problem moving `cem` from Suggests to Depends in the Description... That may be an issue with my computer though, not sure.

**Comment by kosukeimai** [comment]
@alexWhitworth We will look at the `genmatch` issue once we get a chance.  For the meantime, you might want to fix the following error in `NAMESPACE` you see at https://travis-ci.org/kosukeimai/MatchIt

`Packages in Depends field not imported from:
  ‘Matching’ ‘optmatch’ ‘rgenoud’
  These packages need to be imported from (in the NAMESPACE file)
  for when this namespace is loaded but not attached.
`

**Comment by alexWhitworth** [comment]
@kosukeimai done... difference in use of `Imports:` vs `Depends:` in the `DESCRIPTION` file

**Comment by alexWhitworth** [comment]
@kosukeimai When do you expect to have an update on the genetic matching algo? I ask because I'm going to use `MatchIt` in a production pipeline at work but want to wait until this update is pushed through. Thanks!

**Comment by kosukeimai** [comment]
Sorry for the delay @alexWhitworth I don't see any problem here.  The default in `GenMatch` is `ties = TRUE`, which keeps all ties.  You can set this `FALSE` if you want to just have a single match.  In `MatchIt`, you will do:

``m.out <- matchit(treat ~ age + educ + black + hispan + married + nodegree + re74 + re75, data = lalonde, method = "genetic", distance = "logit", ties = FALSE)``

Let me know if this makes sense to you.

**Comment by alexWhitworth** [comment]
@kosukeimai The problem is with the return `m.out$match.matrix`. The column of NAs match `get_matches` fail.

```
m.out <- matchit(treat ~ age + educ + black + hispan + married + nodegree +
                     re74 + re75, data = lalonde, method = "genetic")
# column of all NAs
head(m.out$match.matrix)
     1         2 
NSW1 "PSID368" NA
NSW2 "PSID341" NA
NSW3 "PSID416" NA
NSW4 "PSID423" NA
NSW5 "PSID400" NA

m.out2 <- matchit(treat ~ age + educ + black + hispan + married + nodegree +
                     re74 + re75, data = lalonde, method = "genetic", ties= FALSE)
# no problem with NA column
head(m.out2$match.matrix)
     1        
NSW1 "PSID368"
NSW2 "PSID265"
NSW3 "PSID189"
NSW4 "PSID423"
NSW5 "PSID400"
NSW6 "PSID372"
NSW6 "PSID253"
```

Also, use of ratio != 1 doesn't work:

```
m.out3 <- matchit(treat ~ age + educ + black + hispan + married + nodegree +
                     re74 + re75, data = lalonde, method = "genetic", ratio= 3)
Error in out[out[, 1] == tind[i], 2:(ratio + 1)] : 
  subscript out of bounds
```

**Comment by alexWhitworth** [comment]
@thegaryking for `method= "cem"`, ratio also seems problematic. Is a non 1-1 ratio for cem not supported?

```
m.out <- matchit(treat ~ age + educ + black + hispan + married + nodegree
                 + re74 + re75, data = lalonde, method = "cem", ratio= 1)
m.out3 <- matchit(treat ~ age + educ + black + hispan + married + nodegree
                 + re74 + re75, data = lalonde, method = "cem", ratio= 3)
all.equal(m.out, m.out3)
[1] "Component “call”: target, current do not match when deparsed"
all.equal(m.out$subclass, m.out3$subclass) # seems problematic
[1] TRUE
```

**Comment by kosukeimai** [comment]
@alexWhitworth I don't think you understood my original comment.  Genetic matching, by default, includes additional units when there are ties: `ties = TRUE`  If you look at the output object carefully, you will see that not all elements are `NA`.  As for ratio matching, I do not know genetic matching allows for such options.

**Comment by alexWhitworth** [comment]
@kosukeimai You are correct, I did misunderstand you. New commit submitted and tests pass for genetic matching.

**Comment by alexWhitworth** [comment]
@thegaryking You can ignore my prior comment. I've just read the Iacus (2011) paper and realize the  problem with the question. I would however suggest adding a warning to the user for supplying `ratio > 1` for `method= "cem"`.

**Comment by kosukeimai** [comment]
@alexWhitworth We've had a chance to go over the new version of MatchIt you've put together and think that it has all the functionalities of the package (as you said before).  I was going to merge it into the main branch but noticed that your new change led to the travis error.  Any idea what happened here?

**Comment by alexWhitworth** [comment]
@kosukeimai  Thanks for the ping! It looks like I had a copy/paste error in the test script. It should be fixed now--waiting on Travis to re-test--it passes on my local machine. Glad to hear you've reviewed, and are happy with, the changes :).

I've been using the code in production at work without problems.

**Comment by kosukeimai** [comment]
@alexWhitworth Thanks again for these great improvements to MatchIt.

**Pull request merged**
